package com.haitaiinc.hisdb.drgs.tableadapters;

import com.haitaiinc.data.DBOperator;
import com.haitaiinc.data.tableadapter.TableAdapter;
import com.haitaiinc.hisdb.drgs.BsBaseinfo;

public class BsBaseinfoTableAdapter extends TableAdapter<BsBaseinfo> {

	public BsBaseinfoTableAdapter(DBOperator dbo) {
		super(dbo);
	}

	protected String[] initColumnNames() {
		return new String[]{ "MDTRT_SN", "MDTRT_ID", "PSN_NO", "PATN_IPT_CNT", "IPT_NO", "MEDCASNO", "PSN_NAME", "GEND", "BRDY", "NTLY", "NTLY_NAME", "NWB_BIR_WT", "NWB_ADM_WT", "BIRPLC", "NAPL", "NATY_NAME", "NATY", "CERTNO", "PRFS", "MRG_STAS", "CURR_ADDR_POSCODE", "CURR_ADDR", "PSN_TEL", "RESD_ADDR_PROV", "RESD_ADDR_CITY", "RESD_ADDR_COTY", "RESD_ADDR_SUBD", "RESD_ADDR_VIL", "RESD_ADDR_HOUSNUM", "RESD_ADDR_POSCODE", "RESD_ADDR", "EMPR_TEL", "EMPR_POSCODE", "EMPR_ADDR", "CONER_TEL", "CONER_NAME", "CONER_ADDR", "CONER_RLTS_CODE", "ADM_WAY_NAME", "ADM_WAY_CODE", "TRT_TYPE_NAME", "TRT_TYPE", "ADM_CATY", "ADM_WARD", "ADM_DATE", "DSCG_DATE", "DSCG_CATY", "REFLDEPTCATYNAME", "DSCG_WARD", "IPT_DAYS", "DRUG_DICM_FLAG", "DICM_DRUG_NAME", "DIE_AUTP_FLAG", "ABO_CODE", "ABO_NAME", "RH_CODE", "RH_NAME", "DIE_FLAG", "DEPTDRT_NAME", "CHFDR_NAME", "ATDDR_NAME", "CHFPDR_NAME", "IPT_DR_NAME", "RESP_NURS_NAME", "TRAIN_DR_NAME", "INTN_DR_NAME", "CODR_NAME", "QLTCTRL_DR_NAME", "QLTCTRL_NURS_NAME", "MEDCAS_QLT_NAME", "MEDCAS_QLT_CODE", "QLTCTRL_DATE", "DSCG_WAY_NAME", "DSCG_WAY", "ACP_MEDINS_CODE", "ACP_MEDINS_NAME", "DSCG_31DAYS_RINP_FLAG", "DSCG_31DAYS_RINP_PUP", "DAMG_INTX_EXT_REA", "DAMG_INTX_EXT_REA_DISECODE", "BRN_DAMG_BFADM_COMA_DURA", "BRN_DAMG_AFADM_COMA_DURA", "VENT_USED_DURA", "CNFM_DATE", "PATN_DISE_DIAG_CRSP", "PATN_DISE_DIAG_CRSP_CODE", "IPT_PATN_DIAG_INSCP", "IPT_PATN_DIAG_INSCP_CODE", "DSCG_TRT_RSLT", "DSCG_TRT_RSLT_CODE", "MEDINS_ORGCODE", "AGE", "AISE", "POTE_INTN_DR_NAME", "HBSAG", "HCVAB", "HIVAB", "RESC_CNT", "RESC_SUCC_CNT", "HOSP_DISE_FSTTIME", "HIF_PAY_WAY_NAME", "HIF_PAY_WAY_CODE", "MED_FEE_PAYMTD_NAME", "MEDFEE_PAYMTD_CODE", "SELFPAY_AMT", "MEDFEE_SUMAMT", "ORDN_MED_SERVFEE", "ORDN_TRT_OPRT_FEE", "NURS_FEE", "COM_MED_SERV_OTH_FEE", "PALG_DIAG_FEE", "LAB_DIAG_FEE", "RDHY_DIAG_FEE", "CLNC_DISE_FEE", "NSRGTRT_ITEM_FEE", "CLNC_PHYS_TRT_FEE", "RGTRT_TRT_FEE", "ANST_FEE", "OPRN_FEE", "RHAB_FEE", "TCM_TRT_FEE", "WMFEE", "ABTL_MEDN_FEE", "TCMPAT_FEE", "TCMHERB_FEE", "BLO_FEE", "ALBU_FEE", "GLON_FEE", "CLOTFAC_FEE", "CYKI_FEE", "EXAM_DSPO_MATL_FEE", "TRT_DSPO_MATL_FEE", "OPRN_DSPO_MATL_FEE", "OTH_FEE", "VALI_FLAG", "FIXMEDINS_CODE", "SCSJ", "FLAG", "CZY", "BRXH", "CHFDR_CODE", "ATDDR_CODE", "IPT_DR_CODE", "RESP_NURS_CODE", "TRAIN_DR_CODE", "INTN_DR_CODE", "CODR_CODE", "QLTCTRL_DR_CODE", "QLTCTRL_NURS_CODE", "DEPTDRT_CODE", "OTP_WM_DISE", "WM_DISE_CODE", "OTPCMDISE", "TCMDISECODE", "REFLDEPT_DEPT", "JGDM", "YBZFFS" };
	}

	protected int[] initColumnTypes() {
		return new int[]{ 12, 12, 12, 12, 12, 12, 12, 12, 93, 12, 12, 3, 3, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 93, 93, 12, 12, 12, 3, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 93, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 93, 12, 12, 12, 12, 12, 12, 12, 3, 12, 12, 12, 12, 12, 3, 3, 12, 12, 12, 12, 12, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 12, 12, 93, 3, 12, 3, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 3 };
	}

	protected String initSchemaName() {
		return "DRGS";
	}

	protected String initTableName() {
		return "BS_BASEINFO";
	}
}